/**
 * Constants Index
 * Export all constants from a single entry point
 */

export {
  API_BASE_URL,
  API_TIMEOUT,
  MAX_PADS,
  PAD_PLAY_ANIMATION_DURATION,
  RECORDING_UPDATE_INTERVAL,
  RECORDING_DURATION_DIVISOR,
  TRIM_BAR_DETECTION_THRESHOLD,
  TRIM_BAR_COLOR,
  TRIM_BAR_SELECTED_COLOR,
  WAVEFORM_CONTAINER_WIDTH,
  WAVEFORM_CONTAINER_HEIGHT,
  WAVEFORM_COLOR,
  WAVEFORM_DEFAULT_SAMPLE_STEP,
  PROGRESS_COMPLETE,
  PROGRESS_START,
  KEYBOARD_PAD_MAP,
  THEME_COLORS,
  RECORDING_MIME_TYPE,
  RECORDING_FILE_EXTENSION,
  MAX_SOUNDS_PER_PRESET,
  SOUND_LOAD_TIMEOUT,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
  APP_VERSION,
  APP_NAME,
  APP_DESCRIPTION,
} from "./const";
